name = "PolyaUrnSimulator"
uuid = "4bcabfa6-eebd-487a-8b4a-99bb3a891d86"
authors = ["SUDA Mikihiro <s@sudame.net> and contributors"]
version = "0.1.0"

[deps]
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
